# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20181223_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.CharField(default=b'', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='embededCode',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=b'66a15c5fbbe180f6467d0ea337c6e552', editable=False, max_length=33),
        ),
    ]
